name = "FastSphericalHarmonics"
uuid = "d335c211-7587-445e-a753-f0b1fb7e445f"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.0.0"

[deps]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FastTransforms = "0.12.1"
julia = "1.4"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SpecialFunctions", "Test"]
